version: '3'
services:
  app:
    build: app
    environment: 
      RAILS_ENV: $DOCKER_RAILS_ENV_PRODUCTION
    volumes:
      - ./app:/app
    command: bundle exec puma -C config/puma.rb
    # depends_on:
    #   - db
  nginx:
    build: nginx
    volumes: 
      - ./app:/app
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  # db:
  #   image: mysql
  #   command: mysqld --default-authentication-plugin=mysql_native_password
  #   env_file:
  #     - app/mysql/db.env
  #   volumes:
  #     - ./app/mysql/mysql:/var/lib/mysql
  #     - ./app/tmp/db:/var/lib/mysql/data